'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace TarekWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="TarekWS.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/insert_data", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insert_data(ByVal id As Integer, ByVal firstName As String, ByVal lastName As String, ByVal dofBirth As String, ByVal phone As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/insert_data", ReplyAction:="*")>  _
        Function insert_dataAsync(ByVal id As Integer, ByVal firstName As String, ByVal lastName As String, ByVal dofBirth As String, ByVal phone As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getData(ByVal query As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getData", ReplyAction:="*")>  _
        Function getDataAsync(ByVal query As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/insert_course", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insert_course(ByVal studentID As Integer, ByVal courseID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/insert_course", ReplyAction:="*")>  _
        Function insert_courseAsync(ByVal studentID As Integer, ByVal courseID As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/add_course", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function add_course(ByVal id As Integer, ByVal name As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/add_course", ReplyAction:="*")>  _
        Function add_courseAsync(ByVal id As Integer, ByVal name As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits TarekWS.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of TarekWS.WebService1Soap)
        Implements TarekWS.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function insert_data(ByVal id As Integer, ByVal firstName As String, ByVal lastName As String, ByVal dofBirth As String, ByVal phone As Integer) As Boolean Implements TarekWS.WebService1Soap.insert_data
            Return MyBase.Channel.insert_data(id, firstName, lastName, dofBirth, phone)
        End Function
        
        Public Function insert_dataAsync(ByVal id As Integer, ByVal firstName As String, ByVal lastName As String, ByVal dofBirth As String, ByVal phone As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements TarekWS.WebService1Soap.insert_dataAsync
            Return MyBase.Channel.insert_dataAsync(id, firstName, lastName, dofBirth, phone)
        End Function
        
        Public Function getData(ByVal query As String) As System.Data.DataTable Implements TarekWS.WebService1Soap.getData
            Return MyBase.Channel.getData(query)
        End Function
        
        Public Function getDataAsync(ByVal query As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements TarekWS.WebService1Soap.getDataAsync
            Return MyBase.Channel.getDataAsync(query)
        End Function
        
        Public Function insert_course(ByVal studentID As Integer, ByVal courseID As Integer) As Boolean Implements TarekWS.WebService1Soap.insert_course
            Return MyBase.Channel.insert_course(studentID, courseID)
        End Function
        
        Public Function insert_courseAsync(ByVal studentID As Integer, ByVal courseID As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements TarekWS.WebService1Soap.insert_courseAsync
            Return MyBase.Channel.insert_courseAsync(studentID, courseID)
        End Function
        
        Public Function add_course(ByVal id As Integer, ByVal name As String) As Boolean Implements TarekWS.WebService1Soap.add_course
            Return MyBase.Channel.add_course(id, name)
        End Function
        
        Public Function add_courseAsync(ByVal id As Integer, ByVal name As String) As System.Threading.Tasks.Task(Of Boolean) Implements TarekWS.WebService1Soap.add_courseAsync
            Return MyBase.Channel.add_courseAsync(id, name)
        End Function
    End Class
End Namespace
